name: Secrets scan

on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]

permissions:
  contents: read

jobs:
  secrets-scan:
    name: secrets-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630cea3296fbb84b0592936f83 # v4.2.2
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
